[2022-03-19 17:30:43,133] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: udac_new_v1_dag.task_StageToRedshift.Stage_staging_songs manual__2022-03-19T09:30:39.555104+00:00 [queued]>
[2022-03-19 17:30:43,229] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: udac_new_v1_dag.task_StageToRedshift.Stage_staging_songs manual__2022-03-19T09:30:39.555104+00:00 [queued]>
[2022-03-19 17:30:43,229] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-19 17:30:43,230] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-03-19 17:30:43,231] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-19 17:30:43,274] {taskinstance.py:1264} INFO - Executing <Task(StageToRedshiftOperator): task_StageToRedshift.Stage_staging_songs> on 2022-03-19 09:30:39.555104+00:00
[2022-03-19 17:30:43,278] {standard_task_runner.py:52} INFO - Started process 31787 to run task
[2022-03-19 17:30:43,287] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'udac_new_v1_dag', 'task_StageToRedshift.Stage_staging_songs', 'manual__2022-03-19T09:30:39.555104+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/udac_v1.py', '--cfg-path', '/var/folders/lh/ngst1lt51m9_gyz7qrg2f3nh0000gn/T/tmpigkfgefm', '--error-file', '/var/folders/lh/ngst1lt51m9_gyz7qrg2f3nh0000gn/T/tmp7h2iwj81']
[2022-03-19 17:30:43,294] {standard_task_runner.py:77} INFO - Job 33: Subtask task_StageToRedshift.Stage_staging_songs
[2022-03-19 17:30:43,577] {logging_mixin.py:109} INFO - Running <TaskInstance: udac_new_v1_dag.task_StageToRedshift.Stage_staging_songs manual__2022-03-19T09:30:39.555104+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2022-03-19 17:30:43,652] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=udac_new_v1_dag
AIRFLOW_CTX_TASK_ID=task_StageToRedshift.Stage_staging_songs
AIRFLOW_CTX_EXECUTION_DATE=2022-03-19T09:30:39.555104+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-19T09:30:39.555104+00:00
[2022-03-19 17:30:43,653] {stage_redshift.py:75} INFO - Starting to set aws redshift connection
[2022-03-19 17:30:43,695] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-19 17:30:43,715] {stage_redshift.py:79} INFO - Starting to truncate table, table name: staging_songs!
[2022-03-19 17:30:43,716] {stage_redshift.py:144} INFO - Starting to execute the truncate_table_sql process
[2022-03-19 17:30:43,730] {base.py:70} INFO - Using connection to: id: redshift. Host: redshift-cluster-1.cvmsgkpkbsh2.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: ***, extra: {}
[2022-03-19 17:30:45,332] {dbapi.py:225} INFO - Running statement: 
        TRUNCATE TABLE public.staging_songs
        , parameters: None
[2022-03-19 17:30:46,200] {stage_redshift.py:83} INFO - Starting to copy data from S3 to Redshift table, table name: staging_songs!
[2022-03-19 17:30:46,206] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/***_project/lib/python3.9/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-03-19 17:30:46,207] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/***_project/lib/python3.9/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
[2022-03-19 17:30:46,208] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/***_project/lib/python3.9/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
[2022-03-19 17:30:46,209] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/***_project/lib/python3.9/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
[2022-03-19 17:30:46,209] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/***_project/lib/python3.9/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
[2022-03-19 17:30:46,210] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/***_project/lib/python3.9/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-03-19 17:30:46,211] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/***_project/lib/python3.9/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
[2022-03-19 17:30:46,213] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/***_project/lib/python3.9/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
[2022-03-19 17:30:46,214] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/***_project/lib/python3.9/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
[2022-03-19 17:30:46,214] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/***_project/lib/python3.9/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-03-19 17:30:46,215] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/***_project/lib/python3.9/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
[2022-03-19 17:30:46,216] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/***_project/lib/python3.9/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-03-19 17:30:46,216] {stage_redshift.py:121} INFO - S3_key.format(**context): song_data
[2022-03-19 17:30:46,216] {stage_redshift.py:125} INFO - Starting to execute the copy_sql_statement process
[2022-03-19 17:30:46,224] {base.py:70} INFO - Using connection to: id: redshift. Host: redshift-cluster-1.cvmsgkpkbsh2.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: ***, extra: {}
[2022-03-19 17:30:48,050] {dbapi.py:225} INFO - Running statement: 
        COPY staging_songs
        FROM 's3://udacity-dend/song_data'
        ACCESS_KEY_ID 'AKIAUW7BQYXKOEMAW7ES'
        SECRET_ACCESS_KEY '***'
        FORMAT AS JSON 'auto'
        REGION AS 'us-west-2'
        , parameters: None
[2022-03-19 17:32:34,564] {local_task_job.py:191} WARNING - The recorded hostname 1.0.0.127.in-addr.arpa does not match this instance's hostname oneforall-nickdemacbook-pro.local
[2022-03-19 17:32:34,573] {process_utils.py:120} INFO - Sending Signals.SIGTERM to group 31787. PIDs of all processes in the group: [31787]
[2022-03-19 17:32:34,574] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 31787
[2022-03-19 17:33:34,584] {process_utils.py:138} WARNING - process psutil.Process(pid=31787, name='python3.9', status='running', started='17:30:43') did not respond to SIGTERM. Trying SIGKILL
[2022-03-19 17:33:34,588] {process_utils.py:75} INFO - Sending the signal Signals.SIGKILL to group 31787
[2022-03-19 17:33:34,596] {process_utils.py:70} INFO - Process psutil.Process(pid=31787, name='python3.9', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='17:30:43') (31787) terminated with exit code Negsignal.SIGKILL
[2022-03-19 17:33:34,596] {standard_task_runner.py:133} ERROR - Job 33 was killed before it finished (likely due to running out of memory)
