[2022-03-19 17:11:51,268] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: udac_new_v1_dag.task_StageToRedshift.Stage_staging_songs scheduled__2022-03-19T08:00:00+00:00 [queued]>
[2022-03-19 17:11:51,278] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: udac_new_v1_dag.task_StageToRedshift.Stage_staging_songs scheduled__2022-03-19T08:00:00+00:00 [queued]>
[2022-03-19 17:11:51,279] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-19 17:11:51,279] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-03-19 17:11:51,279] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-19 17:11:51,288] {taskinstance.py:1264} INFO - Executing <Task(StageToRedshiftOperator): task_StageToRedshift.Stage_staging_songs> on 2022-03-19 08:00:00+00:00
[2022-03-19 17:11:51,291] {standard_task_runner.py:52} INFO - Started process 28833 to run task
[2022-03-19 17:11:51,297] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'udac_new_v1_dag', 'task_StageToRedshift.Stage_staging_songs', 'scheduled__2022-03-19T08:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/udac_v1.py', '--cfg-path', '/var/folders/lh/ngst1lt51m9_gyz7qrg2f3nh0000gn/T/tmpj58mx3py', '--error-file', '/var/folders/lh/ngst1lt51m9_gyz7qrg2f3nh0000gn/T/tmpoi9nkw7s']
[2022-03-19 17:11:51,299] {standard_task_runner.py:77} INFO - Job 26: Subtask task_StageToRedshift.Stage_staging_songs
[2022-03-19 17:11:51,350] {logging_mixin.py:109} INFO - Running <TaskInstance: udac_new_v1_dag.task_StageToRedshift.Stage_staging_songs scheduled__2022-03-19T08:00:00+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2022-03-19 17:11:51,405] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=udac_new_v1_dag
AIRFLOW_CTX_TASK_ID=task_StageToRedshift.Stage_staging_songs
AIRFLOW_CTX_EXECUTION_DATE=2022-03-19T08:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-19T08:00:00+00:00
[2022-03-19 17:11:51,405] {stage_redshift.py:75} INFO - Starting to set aws redshift connection
[2022-03-19 17:11:51,414] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-19 17:11:51,429] {stage_redshift.py:79} INFO - Starting to truncate table, table name: staging_songs!
[2022-03-19 17:11:51,429] {stage_redshift.py:144} INFO - Starting to execute the truncate_table_sql process
[2022-03-19 17:11:51,438] {base.py:70} INFO - Using connection to: id: redshift. Host: redshift-cluster-1.cvmsgkpkbsh2.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: ***, extra: {}
[2022-03-19 17:11:53,716] {dbapi.py:225} INFO - Running statement: 
        TRUNCATE TABLE public.staging_songs
        , parameters: None
[2022-03-19 17:11:54,841] {stage_redshift.py:83} INFO - Starting to copy data from S3 to Redshift table, table name: staging_songs!
[2022-03-19 17:11:54,847] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/***_project/lib/python3.9/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-03-19 17:11:54,848] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/***_project/lib/python3.9/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
[2022-03-19 17:11:54,850] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/***_project/lib/python3.9/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
[2022-03-19 17:11:54,851] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/***_project/lib/python3.9/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
[2022-03-19 17:11:54,852] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/***_project/lib/python3.9/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
[2022-03-19 17:11:54,853] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/***_project/lib/python3.9/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-03-19 17:11:54,853] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/***_project/lib/python3.9/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
[2022-03-19 17:11:54,855] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/***_project/lib/python3.9/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
[2022-03-19 17:11:54,855] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/***_project/lib/python3.9/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
[2022-03-19 17:11:54,856] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/***_project/lib/python3.9/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-03-19 17:11:54,858] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/***_project/lib/python3.9/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
[2022-03-19 17:11:54,859] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/***_project/lib/python3.9/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-03-19 17:11:54,859] {stage_redshift.py:121} INFO - S3_key.format(**context): song_data
[2022-03-19 17:11:54,859] {stage_redshift.py:125} INFO - Starting to execute the copy_sql_statement process
[2022-03-19 17:11:54,867] {base.py:70} INFO - Using connection to: id: redshift. Host: redshift-cluster-1.cvmsgkpkbsh2.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: ***, extra: {}
[2022-03-19 17:11:56,847] {dbapi.py:225} INFO - Running statement: 
        COPY staging_songs
        FROM 's3://udacity-dend/song_data'
        ACCESS_KEY_ID 'AKIAUW7BQYXKOEMAW7ES'
        SECRET_ACCESS_KEY '***'
        FORMAT AS JSON 'auto'
        REGION AS 'us-west-2'
        , parameters: None
[2022-03-19 17:13:52,605] {local_task_job.py:191} WARNING - The recorded hostname 1.0.0.127.in-addr.arpa does not match this instance's hostname oneforall-nickdemacbook-pro.local
[2022-03-19 17:13:52,612] {process_utils.py:120} INFO - Sending Signals.SIGTERM to group 28833. PIDs of all processes in the group: [28833]
[2022-03-19 17:13:52,612] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 28833
[2022-03-19 17:14:52,615] {process_utils.py:138} WARNING - process psutil.Process(pid=28833, name='python3.9', status='running', started='17:11:51') did not respond to SIGTERM. Trying SIGKILL
[2022-03-19 17:14:52,618] {process_utils.py:75} INFO - Sending the signal Signals.SIGKILL to group 28833
[2022-03-19 17:14:52,625] {process_utils.py:70} INFO - Process psutil.Process(pid=28833, name='python3.9', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='17:11:51') (28833) terminated with exit code Negsignal.SIGKILL
[2022-03-19 17:14:52,626] {standard_task_runner.py:133} ERROR - Job 26 was killed before it finished (likely due to running out of memory)
